/*
 * GENERATO da tools/remove-bg.py — non modificare a mano.
 * Elenco delle illustrazioni da mettere in cache all'installazione.
 * Verificato da tools/check-assets.mjs, che fallisce se un PNG
 * esiste ma non compare qui.
 */
self.ART_ASSETS = [
  'assets/img/art/sp-barky.png',
  'assets/img/art/sp-bird.png',
  'assets/img/art/sp-bone.png',
  'assets/img/art/sp-castle.png',
  'assets/img/art/sp-cat.png',
  'assets/img/art/sp-cats.png',
  'assets/img/art/sp-claw.png',
  'assets/img/art/sp-cold.png',
  'assets/img/art/sp-dinosaur.png',
  'assets/img/art/sp-dinosaurs.png',
  'assets/img/art/sp-dog.png',
  'assets/img/art/sp-dragon.png',
  'assets/img/art/sp-dragons.png',
  'assets/img/art/sp-egg.png',
  'assets/img/art/sp-eggs.png',
  'assets/img/art/sp-eye.png',
  'assets/img/art/sp-fast.png',
  'assets/img/art/sp-fish.png',
  'assets/img/art/sp-flamup.png',
  'assets/img/art/sp-glimmer.png',
  'assets/img/art/sp-goldwing.png',
  'assets/img/art/sp-happy.png',
  'assets/img/art/sp-horn.png',
  'assets/img/art/sp-hot.png',
  'assets/img/art/sp-knight.png',
  'assets/img/art/sp-monster.png',
  'assets/img/art/sp-moon.png',
  'assets/img/art/sp-nest.png',
  'assets/img/art/sp-numo.png',
  'assets/img/art/sp-pepe.png',
  'assets/img/art/sp-prisma.png',
  'assets/img/art/sp-rocktail.png',
  'assets/img/art/sp-sad.png',
  'assets/img/art/sp-shield.png',
  'assets/img/art/sp-slow.png',
  'assets/img/art/sp-splashy.png',
  'assets/img/art/sp-star.png',
  'assets/img/art/sp-stars.png',
  'assets/img/art/sp-stellina.png',
  'assets/img/art/sp-sun.png',
  'assets/img/art/sp-sword.png',
  'assets/img/art/sp-tail.png',
  'assets/img/art/sp-tooth.png',
  'assets/img/art/sp-torrek.png',
  'assets/img/art/sp-tree.png',
  'assets/img/art/sp-umbra.png',
  'assets/img/art/sp-wing.png',
  'assets/img/art/sp-wizard.png'
];
